name: Compile to PDF
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write  # Changed from 'read' to 'write' to allow tagging
  id-token: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper tagging

    - name: Generate tag
      id: tag
      run: |
        # Create a timestamp-based tag
        TAG="resume-$(date +'%Y%m%d-%H%M%S')"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"

    - name: Create and push tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag ${{ steps.tag.outputs.tag }}
        git push origin ${{ steps.tag.outputs.tag }}

  compile:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile with latex-action
      uses: xu-cheng/latex-action@3.3.0
      with:
        root_file: |
            main.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: main.pdf

  release:
    runs-on: ubuntu-latest
    needs: [create-tag, compile]
    steps:
    - name: Download PDF artifact
      uses: actions/download-artifact@v4
      with:
        name: resume

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.create-tag.outputs.tag }}
        name: "Resume ${{ needs.create-tag.outputs.tag }}"
        files: main.pdf
        body: |
          Automated resume compilation

          **Commit**: ${{ github.sha }}
          **Branch**: ${{ github.ref_name }}
          **Build Time**: ${{ needs.create-tag.outputs.tag }}
